name: Hello World Test

on: 
  push:
    branches:
      - main  # 监听 main 分支的 push 事件
  pull_request:
    branches:
      - main  # 监听 main 分支的 PR 事件
  workflow_dispatch:  # 允许手动触发

jobs:
  hello-world:
    runs-on: ubuntu-latest  # 运行环境
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # 拉取代码

      - name: Print Hello World
        run: echo "Hello, World!"
